version: "2.4"
services:
    odoo:
        image: $ODOO_IMAGE:$ODOO_MINOR
        build:
            context: ./odoo
            args:
                ODOO_VERSION: $ODOO_MINOR
                UID: "${UID:-1000}"
                GID: "${GID:-1000}"
        environment:
            EMAIL_FROM: "$SMTP_DEFAULT_FROM"
            PGDATABASE: &dbname prod
            PGUSER: &dbuser "$DB_USER"
            DB_FILTER: "$DB_FILTER"
            PROXY_MODE: "$ODOO_PROXY_MODE"
        hostname: "$SMTP_REAL_NON_CANONICAL_DEFAULT"
        tty: true
        volumes:
            - filestore:/var/lib/odoo:z
        labels:
            traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
            traefik.docker.network: "inverseproxy_shared"
            traefik.enable: "true"

            # Labels only for Traefik v1
            traefik.frontend.passHostHeader: "true"
            traefik.longpolling.port: "8072"
            traefik.port: "8069"

            # Labels only for Traefik v2
            traefik.entryPoints.web-secured.address: ":443"
            traefik.entryPoints.web.address: ":80"
            traefik.http.middlewares.web2web-secured.redirectscheme.scheme: "https"
            traefik.http.routers.longpolling.entrypoints: "web-secured"
            traefik.http.routers.longpolling.service: "longpolling"
            traefik.http.routers.web-secured.entrypoints: "web-secured"
            traefik.http.routers.web-secured.service: "odoo"
            traefik.http.routers.web-secured.tls.certresolver: "main-acme"
            traefik.http.routers.web.entrypoints: "web"
            traefik.http.routers.web.middlewares: "web2web-secured"
            traefik.http.routers.web.service: "dummy"
            # HACK https://github.com/containous/traefik/issues/4863#issuecomment-491453743
            traefik.http.services.dummy.loadBalancer.server.url: ""
            traefik.http.services.longpolling.loadBalancer.passHostHeader: "true"
            traefik.http.services.longpolling.loadBalancer.server.port: "8072"
            traefik.http.services.longpolling.loadBalancer.server.scheme: "http"
            traefik.http.services.odoo.loadBalancer.passHostHeader: "true"
            traefik.http.services.odoo.loadBalancer.server.port: "8069"
            traefik.http.services.odoo.loadBalancer.server.scheme: "http"

    db:
        image: tecnativa/postgres-autoconf:${DB_VERSION}-alpine
        shm_size: 512mb
        environment:
            POSTGRES_DB: *dbname
            POSTGRES_USER: *dbuser
            CONF_EXTRA: |
                work_mem = 32MB
        volumes:
            - db:/var/lib/postgresql/data:z

    smtpfake:
        image: mailhog/mailhog

    smtpreal:
        image: tvial/docker-mailserver:latest
        domainname: "$SMTP_REAL_MAILNAME"
        stop_grace_period: 1m
        volumes:
            - mailconfig:/tmp/docker-mailserver:z
            - maildata:/var/mail:z
            - maillogs:/var/log/mail:z
            - maillogssupervisord:/var/log/supervisor:z
            - mailstate:/var/mail-state:z
        cap_add:
            - SYS_PTRACE
        environment:
            DEFAULT_RELAY_HOST: "[$SMTP_REAL_RELAY_HOST]:$SMTP_REAL_RELAY_PORT"
            DMS_DEBUG: 0
            ENABLE_SRS: 1
            ONE_DIR: 1
            PERMIT_DOCKER: connected-networks
            POSTFIX_MESSAGE_SIZE_LIMIT: 52428800 # 50 MiB
            RELAY_HOST: "$SMTP_REAL_RELAY_HOST"
            RELAY_PORT: "$SMTP_REAL_RELAY_PORT"
            RELAY_USER: "$SMTP_REAL_RELAY_USER"
            SMTP_ONLY: 1
            SRS_DOMAINNAME: "$SMTP_REAL_NON_CANONICAL_DEFAULT"
            SRS_EXCLUDE_DOMAINS: "$SMTP_REAL_CANONICAL_DOMAINS"
            SRS_SENDER_CLASSES: envelope_sender,header_sender

    backup:
        image: tecnativa/duplicity:postgres-s3
        hostname: backup
        domainname: "$DOMAIN_PROD"
        init: true
        environment:
            DST: "s3://s3.amazonaws.com/$BACKUP_S3_BUCKET"
            EMAIL_FROM: "$BACKUP_EMAIL_FROM"
            EMAIL_TO: "$BACKUP_EMAIL_TO"
            PGDATABASE: *dbname
            PGUSER: *dbuser
            SMTP_HOST: smtplocal
            TZ: "$BACKUP_TZ"
        volumes:
            - backup_cache:/root:z
            - filestore:/mnt/backup/src/odoo:z
